services:
  catalogo-tintas-pg:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=catalogo_tintas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d catalogo_tintas"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - packages/api/.env
    environment:
      - DATABASE_URL=postgresql://docker:docker@catalogo-tintas-pg:5432/catalogo_tintas?schema=public
    depends_on:
      catalogo-tintas-pg:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: /app/docker-entrypoint.sh

volumes:
  pgdata:
